### ISSUE TITLE
MvpAppCompatActivity not found 

### ISSUE THREAD

**Issue by CrazyCoderAndroid** [moxy-community/Moxy#102]
import moxy.MvpAppCompatActivity; shows red line showing cannot resolve symbol MvpAppCompatActivity.

build.gradle(app)

implementation "com.github.moxy-community:moxy:2.1.2"
    annotationProcessor "com.github.moxy-community:moxy-compiler:2.1.1"

**Comment by alaershov** [comment]
Of course it does, `MvpAppCompatActivity` is a class from other artifact:
AndroidX:
`implementation "com.github.moxy-community:moxy-androidx:$moxyVersion"`
AppCompat:
`implementation "com.github.moxy-community:moxy-app-compat:$moxyVersion"`

**Comment by CrazyCoderAndroid** [comment]
ok. Thanks
