### ISSUE TITLE
Set up direct publishing to Maven Central

### ISSUE THREAD

**Issue by alaershov** [moxy-community/Moxy#124]
JCenter is done:
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

We need to set up artifact publishing directly to Maven ([Chris Banes can help us with that](https://chris.banes.dev/publishing-to-maven-central/)), or explore other publishing options: [Github Packages](https://docs.github.com/en/packages/guides/configuring-gradle-for-use-with-github-packages) for instance.

**Comment by dzmitryk-dev** [comment]
Hi guys. Have you started working on it?

**Comment by alaershov** [comment]
@dzkoirn not yet

**Comment by dzmitryk-dev** [comment]
So, maybe I may try to help you there if you need

**Comment by alaershov** [comment]
PRs are always welcome, especially if you have some relevant experience with publishing and can do it right)
