### ISSUE TITLE
IDE plugin for setting View strategies

### ISSUE THREAD

**Issue by Maksim-Novikov** [moxy-community/Moxy#125]
Hello everyone!

About year ago I created plugin for moxy strategies 
https://github.com/Maksim-Novikov/moxy-strategy-plugin
https://plugins.jetbrains.com/plugin/13679-moxy-strategy

And now I finally have some time, to develop   it.
What do you will be better:

1) Just add link to it in Readmy 
2) Add folder into this project

**Comment by alaershov** [comment]
Awesome work @Maksim-Novikov!

It needs to be tested thoroughly, there recently were some changes in strategy resolution: https://github.com/moxy-community/Moxy/issues/70
And there is also an ongoing issue with multi module projects: https://github.com/moxy-community/Moxy/issues/101
The plugin needs to be consistent with moxy compiler behavior to avoid false warnings.

I think we'll start with a link in Readme, and see how the plugin works)

Also, maybe you'd like to consider consider using short aliases for strategies, like `@AddToEndSingle`.

**Comment by Maksim-Novikov** [comment]
@alaershov  I added plugin to readme
https://github.com/moxy-community/Moxy/pulls

Also added alias strategies to plugin

**Comment by alaershov** [comment]
Good job, thanks!
