### ISSUE TITLE
Kapt issue

### ISSUE THREAD

**Issue by pavelpoley** [moxy-community/Moxy#129]
Not sure where the problem come from, but I have described the issue here:
https://stackoverflow.com/questions/66941602/kapt-dependency-issue

**Comment by alaershov** [comment]
If you're using Kotlin, you should use kapt instead of annotationProcessor. If not, you don't need the kapt plugin.

**Comment by pavelpoley** [comment]
I have removed annotationProcessor, added `kapt "com.github.moxy-community:moxy-compiler:$moxyVersion"`, cleaned, unfortunately same issue in runtime.

**Comment by alaershov** [comment]
Unfortunately "dagger stops compile" is not enough to investigate the issue, please provide a sample project to reproduce it.
