### ISSUE TITLE
moxy-compiler tests are broken in develop branch

### ISSUE THREAD

**Issue by bejibx** [moxy-community/Moxy#23]
Hi! I was trying to make PR similar to what I made to original moxy repo ([this](https://github.com/Arello-Mobile/Moxy/pull/259) one) but I find out compiler tests are completely broken in develop branch. So to properly test my changes I have to fix existing tests first, which to be honest I don't have time and motivation to do. Is there some branch with fixed tests I don't know about or tests are broken and everyone ok about it?

**Comment by asitnkova** [comment]
Tests are indeed broken, as we rewrote annotation processor quite a bit. It is planned to refactor tests in near future.

**Comment by asitnkova** [comment]
They are actually fixed in https://github.com/moxy-community/Moxy/pull/20
