### ISSUE TITLE
Add step by step migration guide

### ISSUE THREAD

**Issue by asitnkova** [moxy-community/Moxy#32]
For example:

0. If you already using moxy-community, skip to step 3 
1. Replace in path 'com.arello-mobile' to 'com.github.moxy-community'
2. Replace in path all 'com.arellomobile.mvp' на 'moxy'
3. Raise moxy version to latest (2.0-alpha05)
3.5. Moxy is still in alpha, so add to root bulid.gradle 
repositories {
    maven { url "https://dl.bintray.com/moxy-community/maven" }
}
4a. Fix view interfaces without strategies with help of EmptyStrategyHelper
4b. Or, as an option, imitate old moxy behaviour: (root build.gradle)
subprojects {
    afterEvaluate { project ->
        if (project.hasProperty('android')) {
            android.defaultConfig.javaCompileOptions.annotationProcessorOptions.arguments = [
                disableEmptyStrategyCheck: 'true',
                enableEmptyStrategyHelper: 'false',
                defaultMoxyStrategy: 'moxy.viewstate.strategy.AddToEndStrategy'
            ]
        }
    }
}

NOTES:
No mention of global presenters

**Comment by asitnkova** [comment]
Clarification of 4a above: one can add `android.defaultConfig.javaCompileOptions.annotationProcessorOptions.arguments += ['enableEmptyStrategyHelper': 'true']` under android block to enable EmptyStrategyHelper

**Comment by asitnkova** [comment]
Or for kapt
```
kapt {
    arguments {
        arg("enableEmptyStrategyHelper", "true")
    }
}```

**Comment by alaershov** [comment]
The migration guide is ready, please check it out: https://github.com/moxy-community/Moxy/wiki/Migration-Guide-(1.x.x-to-2.x.x)

**Comment by asitnkova** [comment]
Item 5, add mention about @RegisterMoxyReflectorPackages, as it was removed
