### ISSUE TITLE
IllegalArgumentException: couldn't make a guess for View$$State

### ISSUE THREAD

**Issue by dyckster** [moxy-community/Moxy#50]
After migrating from old repo 1.0.13 to Moxy Community 1.0.13 (also tried 2.0-alpha06) and using android-x libraries my project stopped compiling with error:

```
error: Moxy compilation failed; see the compiler error output for details (java.lang.IllegalArgumentException: couldn't make a guess for com.DyDo.yury.rollertutor.app.feature.learn.mvp.view.SaveTrickView$$State)
```
After deleting these classes the problem still persisted with other View classes.

Here is gist with problem classes and gradle files: https://gist.github.com/23092eafcc06d53285392367be31a8f1

I also tried replacing kapt with annotationProcessor in "com.github.moxy-community:moxy-compiler:$moxyVersion". It solved the build problem, but now it seems like new presenters are not getting generated.

**Comment by asitnkova** [comment]
As per [java's naming convention](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html), package names should be all lower case. One of your packages `DyDo` starts with uppercase, which causes compilation to fail. You can fix it by making all the packages in your project start with lowercase.

**Comment by dyckster** [comment]
Unfortunately since the app is already in Google Play, I am afraid I can't to that. Is there any possible workaround?

**Comment by asitnkova** [comment]
I think you can change source code however you like, just leave applicationId as is. 
For moxy to compile you have to have lowercase package names only in View interfaces.

**Comment by dyckster** [comment]
Yep. Looks like you are right! Thanks.
