### ISSUE TITLE
Androidx Presenter null

### ISSUE THREAD

**Issue by JavohirUz** [moxy-community/Moxy#75]
I am using androidx.Added library.Activity extended MvpAppCompatActivity.but Presenter null if I want to use it it is null

**Comment by alaershov** [comment]
Hi! Please provide some sample code for your problem. You can use [Gist](gist.github.com) or share a repository.

**Comment by alaershov** [comment]
@JavohirUz is your problem resolved?

**Comment by xanderblinov** [comment]
Hope issue is resolved. If you have more questions please see [FAQ](https://github.com/moxy-community/Moxy/wiki/FAQ) page
