### ISSUE TITLE
Null moxy presenter

### ISSUE THREAD

**Issue by 5ALEKSEY** [moxy-community/Moxy#79]
Hello everyone. I noticed a problem when i migrate project to androidX.
Build successfull but after launch presenter for my HomeActivity is null.
Everything was great when i used **arello-mobile** library.
Can you help me please? What is my mistake?
Link for _develop_ branch of my repo: https://github.com/5ALEKSEY/PasswordSaver/tree/develop

**Comment by alaershov** [comment]
You did not use Moxy compiler, and because of that, the library generates no code where all the magic happens. Add the following to `app/build.gradle`:
`kapt "com.github.moxy-community:moxy-compiler:$moxyVersion"`
and see if your problem is resolved.

**Comment by 5ALEKSEY** [comment]
@alaershov thank you very much :) you are right.
P.S. for people with the same issue:
if you migrated to androidX and also to this library (_version 2.0.2 in higher_) for first steps you should manage your **defaultConfig** in app gradle file for prevent for first time your **View** methods without strategy annotations. Also you should check providing moxy presenters with Dagger 2.

**Comment by pavelkostyukoff** [comment]
Welcome, but do not tell me how to solve this problem with the Dagger2? @alaershov  @5ALEKSEY 
more precisely that they both worked and dagger and moxy

**Comment by alaershov** [comment]
@Soprano61 there is a sample on how to use Moxy with Dagger in readme. What exactly is your problem?

**Comment by pavelkostyukoff** [comment]
@alaershov Welcome, the problem has been resolved , and I am grateful for your responsiveness )
